###
GET http://localhost:8282/users HTTP/1.1
Content-Type: application/json

###


GET http://localhost:8282/user?id=641142664a7a656c8ec4c167 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8282/userByEmail?email=khangaikhuu@gmail.com HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8282/userGetEmail?email=khangaikhuu@gmail.com HTTP/1.1
Content-Type: application/json

###


POST http://localhost:8282/user HTTP/1.1
Content-Type: application/json

{
    "name": "Simon Sinek",
    "email": "simon-sinek@gmail.com",
    "createdOn": "2010-01-01",
    "lastLogin": "2022-02-03"
}

###


DELETE  http://localhost:8282/findOneAndDeleteUser HTTP/1.1
Content-Type: application/json

{
  "email" : "simon-sinek@gmail.com"
}

###

DELETE  http://localhost:8282/deleteOneUser HTTP/1.1
Content-Type: application/json

{
  "id" : "641142664a7a656c8ec4c167"
}

###

DELETE  http://localhost:8282/findByIdAndDeleteUser HTTP/1.1
Content-Type: application/json

{
  "id" : "641142664a7a656c8ec4c167"
}

###

GET http://localhost:8282/userByName HTTP/1.1
Content-Type: application/json

###


GET http://localhost:8282/userByEmail HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8282/updateOneUser HTTP/1.1
Content-Type: application/json

###
###
PUT http://localhost:8282/findAndUpdateOneUser HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8282/findByIdAndUpdateUser HTTP/1.1
Content-Type: application/json

###