POST http://localhost:8080/create HTTP/1.1
Content-Type: application/json

[
    {
        "name": "Washing Dishes",
        "checked" : false
    },
    {
        "name": "Groceries",
        "checked" : false
    },
    {
        "name": "Bathing Kids",
        "checked" : false
    }
]


###
PUT http://localhost:8080/update HTTP/1.1
Content-Type: application/json

[
    {"checked": true},
    {"name": "Bathing Kids"}
]
   

###
GET http://localhost:8080/list HTTP/1.1
Content-Type: application/json


###
DELETE http://localhost:8080/delete HTTP/1.1
Content-Type: application/json

{
    "checked": true
}