POST http://localhost:8080/todo/create HTTP/1.1
Content-Type: application/json

{
    "name": "Washing Dishes",
    "checked" : false,
    "category" : "64192c4d8523559e23836fba"
}



###
PUT http://localhost:8080/update HTTP/1.1
Content-Type: application/json

[
    {"checked": true},
    {"name": "Bathing Kids"}
]
   

###
GET http://localhost:8080/todo/list HTTP/1.1
Content-Type: application/json


###
DELETE http://localhost:8080/delete HTTP/1.1
Content-Type: application/json

{
    "checked": false 
}